### PR TITLE
Add Tabs widget

### PR DESCRIPTION
**Pull request by shkolin**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌

### CODE REVIEW

**Comment by samdark** [comment]
Please press "ready for review" when there are no more changes planned. Thanks.

**Comment by shkolin** [comment]
Okey. Thanks.

**Comment by samdark** [comment]
Would you please take care of Psalm issue?

**Comment by samdark** [comment]
Would you please fix Psalm issue?

**Comment by terabytesoftw** [comment]
@shkolin fix

```php
private function buildOptions(): void
{
    Html::addCssClass($this->options, 'tabs');

    $this->options['id'] ??= "{$this->getId()}-tabs";

    if ($this->size !== '') {
        Html::addCssClass($this->options, $this->size);
    }

    if ($this->alignment !== '') {
        Html::addCssClass($this->options, $this->alignment);
    }

    if ($this->style !== '') {
        Html::addCssClass($this->options, $this->style);
    }
}
``

**Comment by shkolin** [comment]
> Would you please fix Psalm issue?

done.

**Comment by shkolin** [comment]
> @shkolin fix
> 
> ```
> private function buildOptions(): void
> {
>     Html::addCssClass($this->options, 'tabs');
> 
>     $this->options['id'] ??= "{$this->getId()}-tabs";
> 
>     if ($this->size !== '') {
>         Html::addCssClass($this->options, $this->size);
>     }
> 
>     if ($this->alignment !== '') {
>         Html::addCssClass($this->options, $this->alignment);
>     }
> 
>     if ($this->style !== '') {
>         Html::addCssClass($this->options, $this->style);
>     }
> }
> ```

Thanks.

**Comment by samdark** [comment]
👍

**Pull request merged**
